### ISSUE TITLE
Initial plugin

### ISSUE THREAD

**Issue by simonw** [simonw/llm-openrouter#1]
Goal is to allow people to `llm install llm-openrouter` and set an API key and instantly get access to the full set of `openrouter.ai` models - as described in this JSON: https://openrouter.ai/api/v1/models

This works in LLM `main` right now using `extra-openai-models.yml` but I think it could be more usable as a separate plugin:

- https://github.com/simonw/llm/issues/165

Documented here: https://llm.datasette.io/en/latest/other-models.html#extra-http-headers

```yaml
- model_id: claude
  model_name: anthropic/claude-2
  api_base: "https://openrouter.ai/api/v1"
  api_key_name: openrouter
  headers:
    HTTP-Referer: "https://llm.datasette.io/"
    X-Title: LLM
```
