### ISSUE TITLE
Include Model Pricing and Context Limits

### ISSUE THREAD

**Issue by niksite** [simonw/llm-openrouter#21]
Including the model's price in the output, along with the input/output context limits, may be a useful addition:

```
➜  ~ llm models -q claude-3.7
OpenRouter: openrouter/anthropic/claude-3.7-sonnet (aliases: sonnet, context: 200k/8k, price: $3/$15)
```

**Comment by simonw** [comment]
This is sort-of supported now by this new command:

```bash
llm openrouter models
```
Refs:
- #26

**Comment by simonw** [comment]
Actually the output from that command is pretty hard to read: https://gist.github.com/simonw/3abd90c3c5fc84723b59f8bf4aaae530

```json
  {
    "id": "perplexity/sonar-reasoning-pro",
    "name": "Perplexity: Sonar Reasoning Pro",
    "created": 1741313308,
    "description": "Note: Sonar Pro pricing includes Perplexity search pricing. See [details here](https://docs.perplexity.ai/guides/pricing#detailed-pricing-breakdown-for-sonar-reasoning-pro-and-sonar-pro)\n\nSonar Reasoning Pro is a premier reasoning model powered by DeepSeek R1 with Chain of Thought (CoT). Designed for advanced use cases, it supports in-depth, multi-step queries with a larger context window and can surface more citations per search, enabling more comprehensive and extensible responses.",
    "context_length": 128000,
    "architecture": {
      "modality": "text->text",
      "tokenizer": "Other",
      "instruct_type": "deepseek-r1"
    },
    "pricing": {
      "prompt": "0.000002",
      "completion": "0.000008",
      "image": "0",
      "request": "0",
      "input_cache_read": "0",
      "input_cache_write": "0",
      "web_search": "0",
      "internal_reasoning": "0"
    },
    "top_provider": {
      "context_length": 128000,
      "max_completion_tokens": null,
      "is_moderated": false
    },
    "per_request_limits": null
  }
```
Re-opening this issue to add an option that human-formats those prices.

**Comment by simonw** [comment]
I may redesign `llm openrouter models` to have a default readable YAML format and a `--json` option for the full JSON.

**Comment by simonw** [comment]
The way they display prices themselves is neatly designed: https://openrouter.ai/models?o=pricing-high-to-low

![Image](https://github.com/user-attachments/assets/9c948972-aca2-47b1-a8fd-c56891fb7ef2)

**Comment by simonw** [comment]
Here's the JSON for that same model:
```json
[
  {
    "id": "microsoft/phi-4-multimodal-instruct",
    "name": "Microsoft: Phi 4 Multimodal Instruct",
    "created": 1741396284,
    "description": "Phi-4 Multimodal Instruct is ...",
    "context_length": 131072,
    "architecture": {
      "modality": "text+image->text",
      "tokenizer": "Other",
      "instruct_type": null
    },
    "pricing": {
      "prompt": "0.00000007",
      "completion": "0.00000014",
      "image": "0.0002476",
      "request": "0",
      "input_cache_read": "0",
      "input_cache_write": "0",
      "web_search": "0",
      "internal_reasoning": "0"
    },
    "top_provider": {
      "context_length": 131072,
      "max_completion_tokens": null,
      "is_moderated": false
    },
    "per_request_limits": null
  }
```

**Comment by simonw** [comment]
Got Claude to write me an imitation of their formatting logic: https://claude.ai/share/871b94d6-f38e-4361-9cd4-83fd237add57

**Comment by simonw** [comment]
```bash
llm openrouter models
```
Now starts like this:
```yaml
- id: latitudegames/wayfarer-large-70b-llama-3.3
  name: LatitueGames: Wayfarer Large 70B Llama 3.3
  context_length: 128,000
  architecture: text->text Llama3
  pricing: prompt $0.7/M, completion $0.7/M

- id: thedrummer/skyfall-36b-v2
  name: TheDrummer: Skyfall 36B V2
  context_length: 64,000
  architecture: text->text Other
  pricing: prompt $0.5/M, completion $0.5/M

- id: microsoft/phi-4-multimodal-instruct
  name: Microsoft: Phi 4 Multimodal Instruct
  context_length: 131,072
  architecture: text+image->text Other
  pricing: prompt $0.07/M, completion $0.14/M, image $0.2476/K
```
Add `--json` to get back the old JSON format instead.
