### ISSUE TITLE
llm openrouter models command

### ISSUE THREAD

**Issue by simonw** [simonw/llm-openrouter#26]
Dumps out the JSON we've stashed here:

https://github.com/simonw/llm-openrouter/blob/373a8f420a945b1d74344f1c8482040bfdf62987/llm_openrouter.py#L12-L17

I added an initial command here:
- #24 

I need to see that list to help with:
- #23

**Comment by simonw** [comment]
Here's what I get from the new command:
```bash
llm openrouter models
```
Output: https://gist.github.com/simonw/3abd90c3c5fc84723b59f8bf4aaae530

**Comment by simonw** [comment]
In #21 I upgraded this so it defaults to outputting YAML. The new default output for `llm openrouter models` looks like this: 

```yaml
- id: latitudegames/wayfarer-large-70b-llama-3.3
  name: LatitueGames: Wayfarer Large 70B Llama 3.3
  context_length: 128,000
  architecture: text->text Llama3
  pricing: prompt $0.7/M, completion $0.7/M

- id: thedrummer/skyfall-36b-v2
  name: TheDrummer: Skyfall 36B V2
  context_length: 64,000
  architecture: text->text Other
  pricing: prompt $0.5/M, completion $0.5/M

- id: microsoft/phi-4-multimodal-instruct
  name: Microsoft: Phi 4 Multimodal Instruct
  context_length: 131,072
  architecture: text+image->text Other
  pricing: prompt $0.07/M, completion $0.14/M, image $0.2476/K
```
Add `--json` for the previous JSON output: https://gist.github.com/simonw/3abd90c3c5fc84723b59f8bf4aaae530
